name = "AOC"
uuid = "060b741a-0962-46c7-a5db-a6b6d93e5b33"
authors = ["Alex Weech <abw@alexweech.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
